name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: imgmagick
        run: sudo apt-get install imagemagick
      - name: install
        run: gem install bundler && bundle
      - name: pages
        run: bundle exec rake wax:pages test
      - name: search
        run: bundle exec rake wax:search main
      - name: derivaties
        run: bundle exec rake wax:derivatives:iiif test
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
